notifications:
  email: false
  slack:
    rooms:
      secure: k5HDOWqewHhNNQloFk5MVtAiHFviU0R+ca+F/QqGNf6gUMLgOBHAWz/0S9xp5QWzbTYlpm6GNStTI45vyVA/Jrj3zlvMkndeR2k7nwctfmY6oQ4zHYkZmBwLIL3yx77VDLUHWnfnrwIAigp7ZR0EPB371lPSEh6P0pmzyEJWVfs5eiTHj+BSKmA9bCC/HqcAHQYjtqm9WrGPCh1vtAN58ESEY7N38vc9BR6hDaZ2K+nz270h82tB72hKoa/OMOFWOq2H9RoJPThD9L5l3B36aOUoCZ+yxOvEpkkF9FC+6vifHAlNHrvVtLPGqfWgHXCbKdFLu7ovJbWXeh95CF1Mh/9rkpUouf+ejtflP7p2FOWMwbOK2G176F5s8U2k/EoXjdrFmJ8l/1NlDwnpP9Y08jqG2Mvt7vpJhxzDqkh0LwTIvz/usWCRMaVZe3hXyRIKyGp16WI5SPMn+rDHOGee11Z+j705Td7TuQa3kjd3+C2xhmdj3/WWO7VqbSrYvb78mwu/Ow6ULT87toEf8pmWP37fz4/ReMxlZJQqEVrV7hO9rUFhZA1V298abuYLXu4MVH+CQcK8TF0bWk+eX39lUr8wT9dHoC4IEI5D7l6mL1XCmdXa1PxeXeX1McEatpLKTA8ZDB96Fjp85YjApGtO9hN+DTvMDoqIuHbkA1hbI8Q=
    on_success: always
    on_failure: always
stages:
- name: PUBLISH
jobs:
  include:
  - stage: PUBLISH
    language: node_js
    node_js:
    - '8'
    script:
    - yarn install
    - npm run docs:build
    deploy:
      provider: pages
      local-dir: docs/.vuepress/dist
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      on:
        branch: master
