notifications:
  email: false
  slack:
    rooms:
      secure: rqQ/kEX42zhsf+Rp4gMUy9HmCorVh0mB1CyyVO0fXt9r51YnNMtUmjcYAwNdoS9ytlcylOYYYvNSkuMQ7/iOjXLCe86sZcCR8q+h69JQUGPc8wJPnUoRRl+pS5BxjWZxEet8cFyDYkQ9yatGhwQ11sR4mwTgBd4Cq42Xv0q86Ei0w2eeTbsutwOJ6YTsCk8RTzwtQQlYNlJaSoZGmuGWdqpszzlsQrQmBu2dmALVkWMNVxefrSUS3L9FPY4gPp/MbWkVfWaQJ9xzQIn0oXGRLpQPyzybJg69o39QEAqRTshScT/JvllErB2gvuhZKDZzJDNu0sP84JYKsU4jp73qskvsHqnDzlATltCezW4fweAbvOOZTdWSSdGNQ4te0ypnw6ziAj9NzyevWZshEGcuOJQhuQv8HLossNkLaoyjYuUQm4/f/1MAoF9fFVkHgSxswIXMrDIZxrYIwCoNVsdzm6u3yOTNdl84gbY5R5gDuf5uewxcCzni90u9slEwr7FWx27NuLYHrG7h8zL47yzLIAJtV8egwNZgPBswFiDEfuZn1+qTGKgCJWROahf6wu/Y7qZn3PoZ1XtQZl01RRJXEp5k9JkBwLVv4Hts7GJaf1RSTpY9DNWhnDH2WQ9jT4UUp81lnsvxWYSmuyOfATxPV7kFOds4WPDtK8LAplEt/IM=
    on_success: always
    on_failure: always
 
stages:
- name: PUBLISH
jobs:
  include:
  - stage: PUBLISH
    language: node_js
    node_js:
    - '8'
    script:
    - yarn install
    - npm run docs:build
    deploy:
      provider: pages
      local-dir: docs/.vuepress/dist
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      on:
        branch: master
