version: '3.5'

services:
  cesiumterrainserver:
    image: geodata/cesium-terrain-server
    volumes:
      - /mnt/data/tilesets/terrain:/data/tilesets/terrain
      - ${DATA_PATH}:/mnt/data
    networks:
      - kargo-network

networks: 
  name: ${DOCKER_NETWORK}
    external: true

