version: '3'
services:
  postgis:
    image: mdillon/postgis:9.6-alpine
    container_name: postgis
    hostname: postgis
    volumes:
      - ./config/postgis:/var/lib/postgresql/data
      - ${DATA_PATH}:/mnt/data
    networks:
      - kargo_network
  
  geoserver:
    image: winsent/geoserver:2.12.0
    container_name: geoserver
    hostname: geoserver
    volumes:
      - ./config/geoserver:/opt/geoserver/data_dir
      - ${DATA_PATH}:/mnt/data
    ports:
      - "${GEOSERVER_PORT}:8080"
    depends_on:
      - postgis
    links:
      - postgis:postgis
    networks:
      - kargo_network
      
  tileservergl:
    image: klokantech/tileserver-gl:v2.2.0
    container_name: tileservergl
    hostname: tileservergl
    volumes:
      - ./config/tileservergl:/data
      - ${DATA_PATH}:/mnt/data
    ports:
      - "${TILESERVERGL_PORT}:80"
    networks:
      - kargo_network

  mapproxy:
    build: https://github.com/yagajs/docker-mapproxy.git#version/1.10.4-alpine
    container_name: mapproxy
    command: mapproxy http
    hostname: mapproxy
    volumes:
      - ./config/mapproxy:/mapproxy
      - ${DATA_PATH}:/mnt/data
    ports:
      - "${MAPPROXY_PORT}:8080"
    depends_on:
      - tileservergl
    links:
      - tileservergl:tileservergl
    networks:
      - kargo_network
      
networks:
    kargo_network:
       external:
          name: ${NETWORK}
