version: '3'
services:
  postgis:
    image: mdillon/postgis:9.6-alpine
    container_name: postgis
    hostname: postgis
    environment:
      - POSTGRES_PASSWORD=kargo
    volumes:
      - ./postgis:/var/lib/postgresql/data
    networks:
      - kargo
  
  geoserver:
    image: winsent/geoserver:2.12.0
    container_name: geoserver
    hostname: geoserver
    environment:
      - VIRTUAL_HOST=geoserver.kalisio.xyz
    volumes:
      - ./geoserver:/opt/geoserver/data_dir
    ports:
      - "8081:8080"
    depends_on:
      - postgis
    links:
      - postgis:postgis
    networks:
      - kargo
      
  tileserver:
    image: klokantech/tileserver-gl:latest
    container_name: tileserver
    hostname: tileserver
    environment:
      - VIRTUAL_HOST=tileserver.kalisio.xyz
    volumes:
      - ./tileserver:/data
    ports:
      - "8082:8080"
    networks:
      - kargo

  mapproxy:
    image: yagajs/mapproxy:1.10.4-alpine
    container_name: mapproxy
    command: mapproxy http
    hostname: mapproxy
    environment:
      - VIRTUAL_HOST=mapproxy.kalisio.xyz
      - VIRTUAL_PORT=8080
    volumes:
      - ./mapproxy:/mapproxy
    ports:
      - "8083:8080"
    depends_on:
      - tileserver
    links:
      - tileserver:tileserver
    networks:
      - kargo
      
  terainserver:
    image: geodata/cesium-terrain-server
    container_name: terrainserver
    hostname: terrainserver
    environment:
      - VIRTUAL_HOST=terrainserver.kalisio.xyz
    volumes:
      - ./terrainserver:/data/tilesets/terrain
    ports:
      - "8084:8080"
    networks:
      - kargo
      
networks:
    kargo:
       external:
          name: kargo
