version: '3'
services:
  postgis:
    image: mdillon/postgis:9.6-alpine
    container_name: postgis
    hostname: postgis
    environment:
      - POSTGRES_PASSWORD=kargo
    volumes:
      - ./postgis:/var/lib/postgresql/data
    networks:
      - kargo
  
  geoserver:
    image: winsent/geoserver:2.12.0
    container_name: geoserver
    hostname: geoserver
    environment:
      - VIRTUAL_HOST=geoserver.kalisio.xyz
    volumes:
      - ./geoserver:/opt/geoserver/data_dir
      - /mnt/data:/mnt/geodata   
    ports:
      - "8081:8080"
    depends_on:
      - postgis
    links:
      - postgis:postgis
    networks:
      - kargo
      
  tileserver-gl:
    image: klokantech/tileserver-gl:v2.2.0
    container_name: tileserver-gl
    hostname: tileserver-gl
    environment:
      - VIRTUAL_HOST=tileserver.kalisio.xyz
    volumes:
      - ./tileserver-gl:/data
      - /mnt/data:/mnt/geodata
    ports:
      - "8082:8080"
    networks:
      - kargo

  mapproxy:
    image: yagajs/mapproxy:1.10.4-alpine
    container_name: mapproxy
    command: mapproxy http
    hostname: mapproxy
    environment:
      - VIRTUAL_HOST=mapproxy.kalisio.xyz
      - VIRTUAL_PORT=8080
    volumes:
      - ./mapproxy:/mapproxy
      - /mnt/data:/mnt/geodata
    ports:
      - "8083:8080"
    depends_on:
      - tileserver-gl
    links:
      - tileserver-gl:tileserver-gl
    networks:
      - kargo
      
networks:
    kargo:
       external:
          name: kargo
