version: '3'
services:
  postgis:
    image: mdillon/postgis:9.6-alpine
    container_name: postgis
    hostname: postgis
    volumes:
      - ./postgis-conf:/var/lib/postgresql/data
      - ${DATA_PATH}:/mnt/data
    networks:
      - ${NETWORK}
  
  geoserver:
    image: winsent/geoserver:2.12.0
    container_name: geoserver
    hostname: geoserver
    volumes:
      - ./geoserver-conf:/opt/geoserver/data_dir
      - ${DATA_PATH}:/mnt/data
    ports:
      - "8081:8080"
    depends_on:
      - postgis
    links:
      - postgis:postgis
    networks:
      - ${NETWORK}
      
  tileserver:
    image: klokantech/tileserver-gl:v2.2.0
    container_name: tileserver-gl
    hostname: tileserver-gl
    volumes:
      - ./tileserver-gl-conf:/data
      - ${DATA_PATH}:/mnt/data
    ports:
      - "8082:80"
    networks:
      - ${NETWORK}

  mapproxy:
    image: yagajs/mapproxy:1.10.4-alpine
    container_name: mapproxy
    command: mapproxy http
    hostname: mapproxy
    volumes:
      - ./mapproxy-conf:/mapproxy
      - ${DATA_PATH}:/mnt/data
    ports:
      - "8083:8080"
    depends_on:
      - tileserver-gl
    links:
      - tileserver-gl:tileserver-gl
    networks:
      - ${NETWORK}
      
networks:
    kargo:
       external:
          name: ${NETWORK}
