version: '3.5'

services:
 geoserver:
    image: kalisio/k-geoserver:0.1.0
    volumes:
      - ./configs/geoserver:/opt/geoserver/data_dir    
      - ${DATA_PATH}:/mnt/data
    networks:
      - kargo-network

networks:
    kargo-network:
      name: ${DOCKER_NETWORK}
      external: true