version: '3.5'

services:
 geoserver:
    image: kalisio/k-geoserver:0.1.0
    volumes:
      - ./configs/geoserver:/opt/geoserver/data_dir    
      - ${DATA_PATH}:/mnt/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/web"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m
    networks:
      - kargo-network

networks:
    kargo-network:
      name: ${DOCKER_NETWORK}
      external: true