version: '3.5'

services:
  mapproxy:
    image: yagajs/mapproxy:1.11-alpine
    environment:
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    command: mapproxy http
    volumes:
      - ${DATA_PATH}:/mnt/data
    networks:
      - kargo-network
      
networks:
    kargo-network:
      name: ${DOCKER_NETWORK}
      external: true
          
