version: '3.5'

services:
  mapproxy:
    image: yagajs/mapproxy:1.11-alpine
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: mapproxy http
    volumes:
      - ./configs/mapproxy:/mapproxy    
      - ${DATA_PATH}:/mnt/data
    depends_on:
      - tileservergl
    networks:
      - kargo-network
      
networks:
    kargo-network:
      name: ${DOCKER_NETWORK}
      external: true
          
