version: '3.3'

services:
  mapproxy:
    image: yagajs/mapproxy:1.11-alpine
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    command: mapproxy http
    volumes:
      - ${DATA_PATH}:/mnt/data
    depends_on:
      - tileservergl
    networks:
      - kargo-network
      
networks:
    kargo-network:
       external:
          name: ${NETWORK}
