version: '3.5'

services:
  maputnik:
    image: kalisio/k-maputnik:0.1.0
    volumes:  
      - ${DATA_PATH}:/mnt/data
    networks:
      - kargo-network
      
networks:
    kargo-network:
      name: ${DOCKER_NETWORK}
      external: true
          
