version: '3.5'

services:
  postgis:
    image: mdillon/postgis:9.6-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
    volumes:
      - ./configs/postgis:/var/lib/postgresql/data
      - ${DATA_PATH}:/mnt/data
    networks:
      - kargo-network

networks:
  kargo-network:
    name: ${DOCKER_NETWORK}
    external: true