version: '3.5'

services: 
  teleray:
    image: kalisio/k-teleray:0.1.0
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
    networks:
      - kargo-network

networks:
  kargo-network:
    name: ${DOCKER_NETWORK}
    external: true
          
