version: '3.3'

services: 
  tileservergl:
    image: klokantech/tileserver-gl:v2.3.1
    volumes:
      - ${DATA_PATH}:/mnt/data
    networks:
      - kargo-network

networks:
    kargo-network:
      name: ${DOCKER_NETWORK}
      external: true
          