# -------------------------------
# MapProxy example configuration.
# -------------------------------
#
# This is a minimal MapProxy configuration.
# See full_example.yaml and the documentation for more options.
#

# Starts the following services:
# Demo:
#     http://localhost:8080/demo
# WMS:
#     capabilities: http://localhost:8080/service?REQUEST=GetCapabilities
# WMTS:
#     capabilities: http://localhost:8080/wmts/1.0.0/WMTSCapabilities.xml
#     first tile: http://localhost:8080/wmts/osm/webmercator/0/0/0.png
# Tile service (compatible with OSM/etc.)
#     first tile: http://localhost:8080/tiles/osm/webmercator/0/0/0.png
# TMS:
#     note: TMS is not compatible with OSM/Google Maps/etc.
#     fist tile: http://localhost:8080/tms/1.0.0/osm/webmercator/0/0/0.png
# KML:
#     initial doc: http://localhost:8080/kml/osm/webmercator

services:
  demo:
  wms:
  tms:
  wmts:

layers:
  - name: osm
    title: OpenStreetMap
    sources: [osm_cache]

  - name: osm-terrain
    title: OpenStreetMap & Terrain data
    sources: [osm-terrain_cache]
     
  - name: s2
    title: ESA S2
    sources: [s2_cache]

  - name: bdortho-5m
    title: IGN BDORTHO (5m)
    sources: [bdortho-5m_cache]

  - name: mosaik
    title: Kalisio mosaic 
    sources: [mosaik_cache]

caches:
  osm_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: [osm_source]
    cache:
      type: s3
      bucket_name: kargo
      directory: cache/osm

  osm-terrain_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: [osm-terrain_source]
    cache:
      type: s3
      bucket_name: kargo
      directory: cache/osm-terrain

  bdortho-5m_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: [bdortho-5m_source]
    cache:
      type: s3
      bucket_name: kargo
      directory: cache/bdortho-5m

  s2_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: [s2_source]
    format: image/jpeg
    cache:
      type: s3
      bucket_name: kargo
      directory: cache/s2

  mosaik_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: [s2_source, bdortho-5m_source, osm-overlay_source]
    format: image/jpeg
    cache:
      type: s3
      bucket_name: kargo
      directory: cache/mosaik

sources:
  osm_source:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://tileservergl/styles/osm-bright/%(z)s/%(x)s/%(y)s.png
 
  osm-terrain_source:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://tileservergl/styles/osm-terrain/%(z)s/%(x)s/%(y)s.png

  osm-overlay_source:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://tileservergl/styles/osm-hybrid/%(z)s/%(x)s/%(y)s.png
    transparent: true

  s2_source:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless_3857/default/g/%(z)s/%(y)s/%(x)s.jpg

  bdortho-5m_source:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://tileservergl/styles/bdortho-5m/%(z)s/%(x)s/%(y)s.png
    transparent: true
    coverage:
      bbox: [-5,41,10,51]
      srs: 'EPSG:4326'  

